# Generated by Django 3.0.7 on 2020-06-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True, verbose_name='名称')),
                ('cover', models.CharField(blank=True, db_column='cover', max_length=255, null=True, verbose_name='封面图')),
                ('short_code', models.CharField(blank=True, db_column='short_code', default='', max_length=255, null=True, verbose_name='简码')),
                ('intro', models.TextField(blank=True, db_column='intro', null=True, verbose_name='简介')),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True, verbose_name='地址')),
                ('linkman', models.CharField(blank=True, db_column='linkman', max_length=255, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=255, null=True, verbose_name='联系电话')),
                ('order_by', models.IntegerField(blank=True, db_column='order_by', default=0, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '校区',
                'verbose_name_plural': '校区管理',
                'db_table': 'school',
                'managed': True,
            },
        ),
    ]
