# Generated by Django 3.0.7 on 2020-08-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200815_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='cover',
            field=models.ImageField(blank=True, db_column='cover', null=True, upload_to='school', verbose_name='封面图'),
        ),
    ]
