# Generated by Django 3.0.7 on 2020-08-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200816_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, db_column='cover', null=True, upload_to='course', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='course',
            name='period',
            field=models.CharField(blank=True, db_column='period', max_length=100, null=True, verbose_name='课程时长'),
        ),
        migrations.AlterField(
            model_name='school',
            name='cover',
            field=models.ImageField(blank=True, db_column='cover', null=True, upload_to='school', verbose_name='封面'),
        ),
    ]
