# Generated by Django 3.0.7 on 2020-08-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200816_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='period_amount',
            field=models.CharField(blank=True, db_column='period_amount', max_length=100, null=True, verbose_name='课时数量'),
        ),
    ]
