# Generated by Django 3.0.7 on 2020-08-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_course_period_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(db_column='photo', default='', upload_to='teacherphoto', verbose_name='职位'),
        ),
    ]
