# Generated by Django 3.0.7 on 2020-08-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20200816_0303'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='teacher',
        #     name='courses',
        #     field=models.ManyToManyField(related_name='CoursesOfTeacher', through='school.TeacherWithCourse', to='school.Course', verbose_name='课程'),
        # ),
        # migrations.AlterModelTable(
        #     name='teacherwithcourse',
        #     table='teacher_course',
        # ),
    ]
