# Generated by Django 3.1 on 2020-08-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20200826_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='period_amount',
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.BooleanField(db_column='status', default=True, verbose_name='上架'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, db_column='start_date', null=True, verbose_name='开课日期'),
        ),
    ]
