# Generated by Django 3.1 on 2020-08-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20200826_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(db_column='status', default=True, verbose_name='状态'),
        ),
    ]
