# Generated by Django 3.1 on 2020-08-31 22:55

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20200828_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': True, 'verbose_name': '课程', 'verbose_name_plural': '课程设置'},
        ),
        migrations.RemoveField(
            model_name='school',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, db_column='intro', null=True, verbose_name='简介'),
        ),
        migrations.DeleteModel(
            name='CourseInSchool',
        ),
    ]
