# Generated by Django 3.1 on 2020-10-02 13:15

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20200831_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, db_column='intro', null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.school', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='school',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, db_column='intro', null=True, verbose_name='简介'),
        ),
    ]
