# Generated by Django 3.1 on 2020-10-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_enroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enroll',
            options={'managed': True, 'verbose_name': '报名咨询', 'verbose_name_plural': '报名咨询管理'},
        ),
    ]
