# Generated by Django 3.1 on 2020-10-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20201017_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='content',
            field=models.CharField(blank=True, default=True, max_length=500, verbose_name='内容'),
        ),
    ]
