# Generated by Django 3.0.7 on 2020-08-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', default='', max_length=255, verbose_name='标题')),
                ('enabled', models.BooleanField(db_column='enabled', default=True, verbose_name='启用')),
                ('order_by', models.IntegerField(blank=True, db_column='order_by', default=0, null=True, verbose_name='排序')),
                ('url', models.CharField(db_column='url', default='', max_length=255, verbose_name='链接')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'db_table': 'friend_links',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HotNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', default='', max_length=255, verbose_name='标题')),
                ('enabled', models.BooleanField(db_column='enabled', default=True, verbose_name='启用')),
                ('order_by', models.IntegerField(blank=True, db_column='order_by', default=0, null=True, verbose_name='排序')),
                ('author', models.CharField(blank=True, db_column='author', default='', max_length=255, null=True, verbose_name='作者')),
                ('link_url', models.CharField(db_column='url', default='', max_length=255, verbose_name='原文链接')),
                ('subtitle', models.CharField(db_column='subtitle', default='', max_length=255, verbose_name='副标题')),
                ('cover', models.ImageField(blank=True, db_column='cover', null=True, upload_to='', verbose_name='封面')),
                ('content', models.TextField(db_column='content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '热点新闻',
                'verbose_name_plural': '热点新闻管理',
                'db_table': 'hot_news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TechnicalArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', default='', max_length=255, verbose_name='标题')),
                ('enabled', models.BooleanField(db_column='enabled', default=True, verbose_name='启用')),
                ('order_by', models.IntegerField(blank=True, db_column='order_by', default=0, null=True, verbose_name='排序')),
                ('author', models.CharField(blank=True, db_column='author', default='', max_length=255, null=True, verbose_name='作者')),
                ('link_url', models.CharField(db_column='url', default='', max_length=255, verbose_name='原文链接')),
                ('subtitle', models.CharField(db_column='subtitle', default='', max_length=255, verbose_name='副标题')),
                ('cover', models.ImageField(blank=True, db_column='cover', null=True, upload_to='', verbose_name='封面')),
                ('content', models.TextField(db_column='content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '技术文章',
                'verbose_name_plural': '技术文章管理',
                'db_table': 'technical_article',
                'managed': True,
            },
        ),
    ]
