# Generated by Django 3.1 on 2020-08-28 00:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_operationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotnews',
            name='content',
            field=tinymce.models.HTMLField(db_column='content', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='technicalarticle',
            name='content',
            field=tinymce.models.HTMLField(db_column='content', verbose_name='内容'),
        ),
    ]
