# Generated by Django 3.1 on 2020-10-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200828_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicalarticle',
            options={'managed': True, 'verbose_name': '活动', 'verbose_name_plural': '活动管理'},
        ),
    ]
