# Generated by Django 3.1 on 2020-10-02 23:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201002_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', default='', max_length=255, verbose_name='标题')),
                ('enabled', models.BooleanField(db_column='enabled', default=True, verbose_name='启用')),
                ('order_by', models.IntegerField(blank=True, db_column='order_by', default=0, null=True, verbose_name='排序')),
                ('author', models.CharField(blank=True, db_column='author', default='', max_length=255, null=True, verbose_name='作者')),
                ('link_url', models.CharField(db_column='url', default='', max_length=255, verbose_name='原文链接')),
                ('subtitle', models.CharField(db_column='subtitle', default='', max_length=255, verbose_name='副标题')),
                ('cover', models.ImageField(blank=True, db_column='cover', null=True, upload_to='techarticle', verbose_name='封面')),
                ('content', tinymce.models.HTMLField(db_column='content', verbose_name='内容')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动管理',
                'db_table': 'active_news',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='technicalarticle',
            options={'managed': True, 'verbose_name': '技术文章', 'verbose_name_plural': '技术文章管理'},
        ),
    ]
