# Generated by Django 3.0.7 on 2020-08-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', default='', max_length=255, verbose_name='名称')),
                ('unit_price', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=8, null=True, verbose_name='单价')),
                ('discount_price', models.DecimalField(db_column='discount_price', decimal_places=2, max_digits=8, null=True, verbose_name='折扣价')),
                ('author', models.CharField(blank=True, db_column='author', max_length=100, null=True, verbose_name='作者')),
                ('sale_url', models.CharField(blank=True, db_column='sale_url', max_length=100, null=True, verbose_name='购买链接')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书管理',
                'db_table': 'book',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', default='', max_length=255, verbose_name='名称')),
                ('unit_price', models.DecimalField(db_column='unit_price', decimal_places=2, max_digits=8, null=True, verbose_name='单价')),
                ('discount_price', models.DecimalField(db_column='discount_price', decimal_places=2, max_digits=8, null=True, verbose_name='折扣价')),
                ('author', models.CharField(blank=True, db_column='author', max_length=100, null=True, verbose_name='作者')),
                ('video_url', models.CharField(blank=True, db_column='video_url', max_length=100, null=True, verbose_name='视频地址')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频管理',
                'db_table': 'video',
                'managed': True,
            },
        ),
    ]
