# Generated by Django 3.0.7 on 2020-08-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, db_column='cover', null=True, upload_to='items', verbose_name='封面'),
        ),
        migrations.AddField(
            model_name='video',
            name='cover',
            field=models.ImageField(blank=True, db_column='cover', null=True, upload_to='items', verbose_name='封面'),
        ),
    ]
