# Generated by Django 3.0.7 on 2020-08-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_book_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True, verbose_name='图书详情'),
        ),
        migrations.AddField(
            model_name='book',
            name='menus_text',
            field=models.TextField(blank=True, db_column='menus_text', null=True, verbose_name='图书目录'),
        ),
    ]
