# Generated by Django 3.1 on 2020-08-24 15:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200823_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=tinymce.models.HTMLField(blank=True, db_column='description', null=True, verbose_name='图书详情'),
        ),
        migrations.AlterField(
            model_name='book',
            name='menus_text',
            field=tinymce.models.HTMLField(blank=True, db_column='menus_text', null=True, verbose_name='图书目录'),
        ),
    ]
